# URL of the API reference table of contents
api_ref_toc_url: http://download.cloud.com/releases/2.2.0/api_2.2.4/TOC_User.html

php:
    class_name: BaseCloudStackClient
    use_camel_case: true

# Camel case values
camel_case:
    values:
    account: account
    accounts: accounts
    accounttype: accountType
    algorithm: algorithm
    allocatedonly: allocatedOnly
    applied: applied
    availability: availability
    available: available
    bits: bits
    bootable: bootable
    cidrlist: cidrList
    description: description
    destzoneid: destzoneId
    deviceid: deviceId
    diskofferingid: diskOfferingId
    displayname: displayName
    displaytext: displayText
    domain: domain
    domainid: domainId
    duration: duration
    enddate: endDate
    endip: endIp
    endport: endPort
    entrytime: entryTime
    forced: forced
    format: format
    forvirtualnetwork: forVirtualNetwork
    gateway: gateway
    group: group
    groupid: groupId
    guestiptype: guestIpType
    haenable: haEnable
    hostid: hostId
    hypervisor: hypervisor
    icmpcode: icmpCode
    icmptype: icmpType
    id: id
    ids: ids
    intervaltype: intervalType
    ipaddress: ipAddress
    ipaddressid: ipAddressId
    iprange: ipRange
    iscleanuprequired: isCleanuPrequired
    isdefault: isDefault
    isextractable: isExtractable
    isfeatured: isFeatured
    isofilter: isoFilter
    ispublic: isPublic
    isready: isReady
    isrecursive: isRecursive
    isshared: isShared
    issystem: isSystem
    jobid: jobId
    keypair: keyPair
    level: level
    maxsnaps: maxSnaps
    mode: mode
    name: name
    netmask: netmask
    networkdomain: networkDomain
    networkid: networkId
    networkids: networkIds
    networkofferingid: networkOfferingId
    op: op
    oscategoryid: osCategoryId
    ostypeid: osTypeId
    page: page
    password: password
    passwordenabled: passwordEnabled
    podid: podId
    policyid: policyId
    privateport: privatePort
    protocol: protocol
    publicipid: publicIpId
    publicport: publicPort
    requireshvm: requireShvm
    resourcetype: resourceType
    schedule: schedule
    securitygroupid: securityGroupId
    securitygroupids: securityGroupIds
    securitygroupname: securityGroupName
    securitygroupnames: securityGroupNames
    serviceofferingid: serviceOfferingId
    size: size
    snapshotid: snapshotId
    snapshottype: snapshotType
    sourcezoneid: sourceZoneId
    specifyvlan: specifyVlan
    startdate: startDate
    startip: startIp
    startport: startPort
    state: state
    templatefilter: templateFilter
    templateid: templateId
    timezone: timezone
    traffictype: trafficType
    type: type
    url: url
    userdata: userData
    userid: userId
    username: userName
    usersecuritygrouplist: userSecurityGroupList
    virtualmachineid: virtualMachineId
    virtualmachineids: virtualMachineIds
    vlan: vlan
    vlanid: vlanId
    volumeid: volumeId
    zoneid: zoneId