# URL of the API reference table of contents
# check out if you have the latest version url here:
# http://cloud.mindtouch.us/CloudStack_Documentation/API_Reference%3A_CloudStack
api_ref_toc_url: http://download.cloud.com/releases/2.2.0/api_2.2.12/TOC_Global_Admin.html 

# Language for generated code (supported: php, python)
language: php

# Generated class name
class_name: CloudStackClient

# Use camel case variable or not
use_camel_case: true

# Camel case values
camel_case:
    account: account
    accountid: accountId
    accounts: accounts
    accounttype: accountType
    algorithm: algorithm
    allocatedonly: allocatedOnly
    allocationstate: allocationState
    applied: applied
    availability: availability
    available: available
    bits: bits
    bootable: bootable
    category: category
    certificate: certificate
    checksum: checksum
    cidrlist: cidrList
    cleanup: cleanUp
    clusterid: clusterId
    clustername: clusterName
    clustertype: clusterType
    component: component
    cpunumber: cpunumber
    cpuspeed: cpuspeed
    customized: customized
    description: description
    destzoneid: destzoneId
    details: details
    deviceid: deviceId
    dhcpprovider: dhcpProvider
    diskofferingid: diskOfferingId
    disksize: diskSize
    displayname: displayName
    displaytext: displayText
    dns1: dns1
    dns2: dns2
    dnssearchorder: dnsSearchOrder
    domain: domain
    domainid: domainId
    domainsuffix: domainSuffix
    duration: duration
    email: email
    enddate: endDate
    endip: endIp
    endport: endPort
    entrytime: entryTime
    fingerprint: fingerprint
    firstname: firstName
    forced: forced
    forcedestroylocalstorage: forceDestroyLocalStorage
    forloadbalancing: forLoadBalancing
    format: format
    forvirtualnetwork: forVirtualNetwork
    gateway: gateway
    group: group
    groupid: groupId
    guestcidraddress: guestCidrAddress
    guestiptype: guestIpType
    haenable: haEnable
    hostid: hostId
    hosttags: hostTags
    hypervisor: hypervisor
    icmpcode: icmpCode
    icmptype: icmpType
    id: id
    ids: ids
    instance: instance
    internaldns1: internalDns1
    internaldns2: internalDns2
    intervaltype: intervalType
    ipaddress: ipAddress
    ipaddressid: ipAddressId
    iprange: ipRange
    iptonetworklist: ipToNetworkList
    iscleanuprequired: isCleanUpRequired
    isdefault: isDefault
    isextractable: isExtractable
    isfeatured: isFeatured
    isofilter: isoFilter
    ispublic: isPublic
    isready: isReady
    isrecursive: isRecursive
    isshared: isShared
    issystem: isSystem
    jobid: jobId
    keyboard: keyboard 
    keypair: keyPair
    keyword: keyword
    lastname: lastName
    level: level
    limitcpuuse: limitCpuUse
    lock: lock
    managedstate: managedState
    max: max
    maxsnaps: maxSnaps
    memory: memory
    mode: mode
    name: name
    netmask: netmask
    networkdeviceparameterlist: networkDeviceParameterList
    networkdevicetype: networkDeviceType
    networkdomain: networkDomain
    networkid: networkId
    networkids: networkIds
    networkofferingid: networkOfferingId
    networkrate: networkRate
    networktype: networkType
    newname: newName
    offerha: offerHa
    op: op
    openfirewall: openFirewall
    oscategoryid: osCategoryId
    ostypeid: osTypeId
    page: page
    pagesize: pageSize
    parentdomainid: parentDomainId
    password: password
    passwordenabled: passwordEnabled
    path: path
    podid: podId
    policyid: policyId
    privateendport: privateEndPort
    privatekey: privateKey
    privateport: privatePort
    protocol: protocol
    publicendport: publicEndPort
    publicipid: publicIpId
    publickey: publicKey
    publicport: publicPort
    requireshvm: requireShvm
    resourcetype: resourceType
    schedule: schedule
    securitygroupenabled: securityGroupEnabled
    securitygroupid: securityGroupId
    securitygroupids: securityGroupIds
    securitygroupname: securityGroupName
    securitygroupnames: securityGroupNames
    serviceofferingid: serviceOfferingId
    size: size
    snapshotid: snapshotId
    snapshottype: snapshotType
    sourcezoneid: sourceZoneId
    specifyvlan: specifyVlan
    startdate: startDate
    startip: startIp
    startport: startPort
    state: state
    storageid: storageId
    storagetype: storageType
    systemvmtype: systemVmType 
    tags: tags
    templatefilter: templateFilter
    templateid: templateId
    templatetag: templateTag
    timezone: timezone
    traffictype: trafficType
    type: type
    url: url
    userapikey: userApiKey
    userdata: userData
    userid: userId
    username: userName
    usersecretkey: userSecretKey
    usersecuritygrouplist: userSecurityGroupList
    virtualmachineid: virtualMachineId
    virtualmachineids: virtualMachineIds
    value: value
    vlan: vlan
    vlanid: vlanId
    volumeid: volumeId
    zoneid: zoneId
